#!/usr/bin/env python3
"""
Generate a small LVGL 9 bitmap font from a TTF, optionally with TABULAR digits.

The dash fonts, all Barlow Condensed Bold (fonts/, SIL OFL 1.1) to match the
MR2 instrument style, and all generated by this script:

    python tools/gen_font.py --size 56 --name dash_font_value_56
    python tools/gen_font.py --size 40 --name dash_font_numeral_40 --chars 0123456789
    python tools/gen_font.py --size 26 --name dash_font_legend_26 --proportional \\
        --chars " %./-0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"

(run from hw/dash_cluster/firmware). The output is generated - regenerate it
rather than editing it.

Tabular digits, the default. A proportional face gives a "1" far less width
than a "4", so a centred reading shuffles sideways every time a digit changes
width. Tabular figures give every digit the same advance. Most faces have
tabular alternates, but they are reached through the OpenType `tnum` feature,
which neither lv_font_conv nor Pillow without libraqm can select - so this does
the equivalent directly: every digit gets the widest digit's advance, with its
glyph centred in the cell. --proportional turns that off, for text.

Why not lv_font_conv: it needs Node, which this machine does not have, and the
format is simple enough to emit directly for a few dozen glyphs.

The format is LVGL's lv_font_fmt_txt, uncompressed, 4 bpp, no kerning - the
same shape lv_font_conv produces with --no-compress --bpp 4. Checked against
lv_font_fmt_txt.c in 9.5.0: 4 bpp pixels are packed high nibble first and run
continuously across rows (stride 0), each glyph starting on a byte boundary;
LV_FONT_FMT_TXT_CMAP_SPARSE_TINY binary-searches offsets from range_start.
Glyph boxes and offsets were compared against LVGL's own lv_font_conv output
for Montserrat 48 and match exactly.
"""

import argparse
import os
import sys

from PIL import Image, ImageDraw, ImageFont

HERE = os.path.dirname(os.path.abspath(__file__))
FIRMWARE = os.path.dirname(HERE)

DEFAULT_FONT = os.path.join(FIRMWARE, "fonts", "BarlowCondensed-Bold.ttf")

# Everything Signal_Format() and the model can put in a value: digits, a sign,
# a decimal point, "--" for no data, "?" for an unknown signal, and a space.
DEFAULT_CHARS = " -.0123456789?"
DIGITS = "0123456789"
BPP = 4


def rasterise(font, ch):
    """One glyph as (box_w, box_h, ofs_x, ofs_y, adv_px, pixels 0..255)."""
    adv = font.getlength(ch)
    left, top, right, bottom = font.getbbox(ch, anchor="ls")
    w, h = right - left, bottom - top
    if w <= 0 or h <= 0:
        return 0, 0, 0, 0, adv, []

    img = Image.new("L", (w, h), 0)
    ImageDraw.Draw(img).text((-left, -top), ch, font=font, fill=255, anchor="ls")

    ink = img.getbbox()
    if ink is None:
        return 0, 0, 0, 0, adv, []
    img = img.crop(ink)
    bw, bh = img.size

    # LVGL: ofs_x is the left bearing, ofs_y the distance from the baseline UP
    # to the bottom of the box. In baseline coordinates y grows downward.
    ofs_x = left + ink[0]
    ofs_y = -(top + ink[3])
    flat = img.get_flattened_data() if hasattr(img, "get_flattened_data") else img.getdata()
    return bw, bh, ofs_x, ofs_y, adv, list(flat)


def pack4(pixels):
    """8-bit coverage to 4 bpp, high nibble first, padded to a byte."""
    out = bytearray()
    nib = [min(15, (p * 15 + 127) // 255) for p in pixels]
    for i in range(0, len(nib), 2):
        hi = nib[i]
        lo = nib[i + 1] if i + 1 < len(nib) else 0
        out.append((hi << 4) | lo)
    return bytes(out)


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--font", default=DEFAULT_FONT)
    ap.add_argument("--size", type=int, required=True)
    ap.add_argument("--name", required=True, help="C symbol, and the output file name")
    ap.add_argument("--chars", default=DEFAULT_CHARS)
    ap.add_argument("--proportional", action="store_true",
                    help="keep each digit's own advance (for text, not readings)")
    ap.add_argument("--out", default=None)
    args = ap.parse_args()

    chars = "".join(sorted(set(args.chars), key=ord))
    out_path = args.out or os.path.join(FIRMWARE, "src", args.name + ".c")

    font = ImageFont.truetype(args.font, args.size)
    glyphs = {ch: rasterise(font, ch) for ch in chars}

    # Line height from the glyphs actually included, the way lv_font_conv does
    # it - not the face's ascender/descender, which allow for accents and
    # brackets this font does not carry and would pad every label.
    inked = [g for g in glyphs.values() if g[0] and g[1]]
    top = max(g[3] + g[1] for g in inked)
    bottom = min(0, min(g[3] for g in inked))
    line_height = top - bottom
    base_line = -bottom

    tabular = not args.proportional and any(d in chars for d in DIGITS)
    cell = 0.0
    if tabular:
        # The widest digit's advance, rounded up to a whole pixel so no digit
        # ever overhangs it.
        cell = max(glyphs[d][4] for d in DIGITS if d in chars)
        cell = float(int(cell) + (0 if cell == int(cell) else 1))

    bitmap = bytearray()
    dsc_lines = ["    {.bitmap_index = 0, .adv_w = 0, .box_w = 0, .box_h = 0, "
                 ".ofs_x = 0, .ofs_y = 0} /* id = 0 reserved */,"]
    bitmap_lines = []

    for ch in chars:
        bw, bh, ofs_x, ofs_y, adv, pixels = glyphs[ch]
        if tabular and ch in DIGITS:
            ofs_x += int(round((cell - adv) / 2.0))
            adv = cell
        index = len(bitmap)
        packed = pack4(pixels)
        bitmap += packed

        shown = ch if ch not in "\\\"" else "\\" + ch
        dsc_lines.append(
            "    {.bitmap_index = %d, .adv_w = %d, .box_w = %d, .box_h = %d, "
            ".ofs_x = %d, .ofs_y = %d}, /* U+%04X \"%s\" */"
            % (index, int(round(adv * 16)), bw, bh, ofs_x, ofs_y, ord(ch), shown))

        bitmap_lines.append("    /* U+%04X \"%s\" */" % (ord(ch), shown))
        for i in range(0, len(packed), 16):
            bitmap_lines.append("    " + ", ".join("0x%02x" % b for b in packed[i:i + 16]) + ",")

    codes = [ord(c) for c in chars]
    start = codes[0]
    unicode_list = ", ".join("0x%x" % (c - start) for c in codes)

    font_rel = os.path.relpath(args.font, FIRMWARE).replace(os.sep, "/")
    command = "python tools/gen_font.py --size %d --name %s" % (args.size, args.name)
    if args.chars != DEFAULT_CHARS:
        command += " --chars \"%s\"" % args.chars
    if args.proportional:
        command += " --proportional"

    src = """/*******************************************************************************
 * GENERATED by tools/gen_font.py - do not edit, regenerate:
 *
 *   %(command)s
 *
 * %(name)s: %(size)d px, %(bpp)d bpp, from %(font)s.
 * %(tabular)s
 * Characters: "%(chars)s"
 *
 * The font's licence is beside the TTF it was made from.
 ******************************************************************************/

#include "lvgl.h"

static LV_ATTRIBUTE_LARGE_CONST const uint8_t glyph_bitmap[] = {
%(bitmap)s
};

static const lv_font_fmt_txt_glyph_dsc_t glyph_dsc[] = {
%(dsc)s
};

static const uint16_t unicode_list_0[] = {
    %(ulist)s
};

static const lv_font_fmt_txt_cmap_t cmaps[] = {
    {
        .range_start = %(start)d, .range_length = %(rlen)d, .glyph_id_start = 1,
        .unicode_list = unicode_list_0, .glyph_id_ofs_list = NULL,
        .list_length = %(count)d, .type = LV_FONT_FMT_TXT_CMAP_SPARSE_TINY
    }
};

static const lv_font_fmt_txt_dsc_t font_dsc = {
    .glyph_bitmap = glyph_bitmap,
    .glyph_dsc = glyph_dsc,
    .cmaps = cmaps,
    .kern_dsc = NULL,
    .kern_scale = 0,
    .cmap_num = 1,
    .bpp = %(bpp)d,
    .kern_classes = 0,
    .bitmap_format = 0,
};

const lv_font_t %(name)s = {
    .get_glyph_dsc = lv_font_get_glyph_dsc_fmt_txt,
    .get_glyph_bitmap = lv_font_get_bitmap_fmt_txt,
    .line_height = %(line_height)d,
    .base_line = %(base_line)d,
    .subpx = LV_FONT_SUBPX_NONE,
    .underline_position = %(ul_pos)d,
    .underline_thickness = %(ul_thick)d,
    .dsc = &font_dsc,
    .fallback = NULL,
    .user_data = NULL,
};
""" % {
        "command": command,
        "name": args.name,
        "size": args.size,
        "bpp": BPP,
        "font": font_rel,
        "tabular": ("Tabular digits: every digit advances %.0f px, so a changing "
                    "reading does not shuffle sideways." % cell) if tabular
                   else "Proportional spacing.",
        "chars": chars.replace("\\", "\\\\").replace("\"", "\\\""),
        "bitmap": "\n".join(bitmap_lines),
        "dsc": "\n".join(dsc_lines),
        "ulist": unicode_list,
        "start": start,
        "rlen": codes[-1] - start + 1,
        "count": len(codes),
        "line_height": line_height,
        "base_line": base_line,
        "ul_pos": -max(1, args.size // 14),
        "ul_thick": max(1, args.size // 24),
    }

    with open(out_path, "w", newline="\r\n") as f:
        f.write(src)

    print("wrote %s: %d glyphs, %d bitmap bytes, line height %d%s"
          % (os.path.relpath(out_path, FIRMWARE), len(chars), len(bitmap), line_height,
             (", digit cell %.0f px" % cell) if tabular else ""))
    return 0


if __name__ == "__main__":
    sys.exit(main())
