#!/usr/bin/env python3
"""
Pre-render the gauge dials with LVGL on the PC and write src/dash_faces.c.

    python tools/face_render/build_faces.py      (from hw/dash_cluster/firmware)

Rerun after changing anything that decides how a dial looks: a gauge's tick
labels or placement in pages.c, UiGauge_CreateScale() in ui_gauge.c, or
lv_conf.h. The firmware refuses a face whose size no longer matches its
element and falls back to drawing the scale live, but it cannot notice changed
tick labels - a stale face would simply show the old numbers.

Builds LVGL itself with MSVC (found through vswhere, as the host tests do),
against the firmware's own lv_conf.h via tools/face_render/lv_conf.h. The
LVGL objects are cached in tools/face_render/build and rebuilt only when their
source or either lv_conf.h is newer; the application sources are always
rebuilt, since the cache cannot see header changes. Reruns take seconds.
"""

import os
import subprocess
import sys
from concurrent.futures import ThreadPoolExecutor

HERE = os.path.dirname(os.path.abspath(__file__))
FIRMWARE = os.path.normpath(os.path.join(HERE, "..", ".."))
SRC = os.path.join(FIRMWARE, "src")
REPO = os.path.normpath(os.path.join(FIRMWARE, "..", "..", ".."))
LVGL = os.path.join(REPO, "external", "lvgl")
BUILD = os.path.join(HERE, "build")
OBJ = os.path.join(BUILD, "obj")
OUT = os.path.join(BUILD, "faces")
GENERATED = os.path.join(SRC, "dash_faces.c")

sys.path.insert(0, os.path.join(FIRMWARE, "test"))
from run_tests import find_vswhere_cl  # noqa: E402

# The firmware sources the renderer needs: the page tables and the dial.
# pages.c pulls in the signal store for its warning takeover.
APP_SOURCES = [
    os.path.join(HERE, "face_render.c"),
    os.path.join(SRC, "ui_gauge.c"),
    os.path.join(SRC, "dash_font_numeral_40.c"),
    os.path.join(SRC, "dash_font_legend_26.c"),
    os.path.join(SRC, "pages.c"),
    os.path.join(SRC, "signal_store.c"),
    os.path.join(SRC, "signals.c"),
]

CFLAGS = [
    "/nologo", "/O2", "/std:c11", "/w", "/utf-8",
    "/DLV_CONF_INCLUDE_SIMPLE",
    "/I" + HERE,            # its lv_conf.h, wrapping the firmware's
    "/I" + LVGL,            # "lvgl.h"
    "/I" + SRC,
]


def lvgl_sources():
    out = []
    for root, _, files in os.walk(os.path.join(LVGL, "src")):
        for f in files:
            if f.endswith(".c"):
                out.append(os.path.join(root, f))
    return sorted(out)


def obj_for(src):
    # Flatten the path: LVGL reuses file names across directories.
    rel = os.path.relpath(src, REPO).replace(os.sep, "_").replace(":", "")
    return os.path.join(OBJ, os.path.splitext(rel)[0] + ".obj")


# The object cache knows nothing about #include, so it is kept to where that
# is safe. The application sources - a handful of files sharing firmware
# headers like pages.h - are always rebuilt: a cached face_render.obj built
# against an older FaceElement_t once walked Pages[] with the wrong struct
# size and crashed. LVGL's objects are reused, but only while they are newer
# than both lv_conf.h files as well as their own source.
LV_CONFS = [os.path.join(FIRMWARE, "lv_conf.h"), os.path.join(HERE, "lv_conf.h")]


def compile_one(cl, env, src, cacheable):
    obj = obj_for(src)
    if cacheable and os.path.exists(obj):
        newest = max([os.path.getmtime(src)] + [os.path.getmtime(c) for c in LV_CONFS])
        if os.path.getmtime(obj) >= newest:
            return None
    r = subprocess.run([cl] + CFLAGS + ["/c", src, "/Fo:" + obj],
                       env=env, capture_output=True, text=True)
    if r.returncode != 0:
        return "%s\n%s%s" % (src, r.stdout, r.stderr)
    return None


def write_generated(manifest):
    lines = [
        "/*******************************************************************************",
        " * GENERATED by tools/face_render/build_faces.py - do not edit, regenerate.",
        " *",
        " * The gauge dials, rendered on the PC by LVGL itself with the firmware's own",
        " * lv_conf.h and UiGauge_CreateScale(). RGB565, high byte first - the panel's",
        " * order - so the image is copied to the draw buffer without conversion.",
        " ******************************************************************************/",
        "",
        "#include \"dash_faces.h\"",
        "",
    ]
    entries = []
    for page, elem, w, h in manifest:
        name = "face_p%d_e%d" % (page, elem)
        data = open(os.path.join(OUT, "p%d_e%d.bin" % (page, elem)), "rb").read()
        if len(data) != w * h * 2:
            sys.exit("%s: %d bytes, expected %d" % (name, len(data), w * h * 2))
        lines.append("static LV_ATTRIBUTE_LARGE_CONST const uint8_t %s_map[] = {" % name)
        for i in range(0, len(data), 24):
            lines.append("    " + ",".join("0x%02x" % b for b in data[i:i + 24]) + ",")
        lines.append("};")
        lines.append("")
        lines.append("static const lv_image_dsc_t %s = {" % name)
        lines.append("    .header = {")
        lines.append("        .magic = LV_IMAGE_HEADER_MAGIC,")
        lines.append("        .cf = LV_COLOR_FORMAT_RGB565_SWAPPED,")
        lines.append("        .flags = 0,")
        lines.append("        .w = %d," % w)
        lines.append("        .h = %d," % h)
        lines.append("        .stride = %d," % (w * 2))
        lines.append("    },")
        lines.append("    .data_size = sizeof(%s_map)," % name)
        lines.append("    .data = %s_map," % name)
        lines.append("};")
        lines.append("")
        entries.append("    { %d, %d, %d, %d, &%s }," % (page, elem, w, h, name))

    lines.append("const DashFace_t DashFaces[] =")
    lines.append("{")
    lines.extend(entries)
    lines.append("};")
    lines.append("")
    lines.append("const uint8_t DashFaceCount = (uint8_t)(sizeof(DashFaces) / sizeof(DashFaces[0]));")
    lines.append("")

    with open(GENERATED, "w", newline="\r\n") as f:
        f.write("\n".join(lines))


def main():
    if not os.path.exists(os.path.join(LVGL, "lvgl.h")):
        sys.exit("LVGL not found at %s" % LVGL)

    cl, env = find_vswhere_cl()
    if cl is None:
        sys.exit("MSVC not found - install the Visual Studio Build Tools")

    os.makedirs(OBJ, exist_ok=True)
    os.makedirs(OUT, exist_ok=True)

    sources = lvgl_sources() + APP_SOURCES
    print("compiling %d sources with MSVC (cached objects are reused)..." % len(sources))
    workers = max(2, (os.cpu_count() or 4))
    with ThreadPoolExecutor(max_workers=workers) as pool:
        app = set(APP_SOURCES)
        errors = [e for e in pool.map(lambda s: compile_one(cl, env, s, s not in app), sources) if e]
    if errors:
        for e in errors[:5]:
            print(e)
        sys.exit("%d source(s) failed to compile" % len(errors))

    exe = os.path.join(BUILD, "face_render.exe")
    rsp = os.path.join(BUILD, "link.rsp")
    with open(rsp, "w") as f:
        f.write("\n".join('"%s"' % obj_for(s) for s in sources))
    r = subprocess.run([cl, "/nologo", "/Fe:" + exe, "@" + rsp],
                       env=env, capture_output=True, text=True)
    if r.returncode != 0:
        sys.stdout.write(r.stdout[-4000:])
        sys.exit("link failed")

    r = subprocess.run([exe, OUT], env=env, capture_output=True, text=True)
    sys.stdout.write(r.stdout)
    if r.returncode != 0:
        sys.stderr.write(r.stderr)
        sys.exit("renderer failed")

    manifest = []
    for line in open(os.path.join(OUT, "faces.txt")):
        if line.strip():
            manifest.append(tuple(int(x) for x in line.split()))

    write_generated(manifest)
    print("wrote %s (%d face(s))" % (os.path.relpath(GENERATED, FIRMWARE), len(manifest)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
