

;
; ษอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
; บ	This file is generated by The Interactive Disassembler (IDA)	    บ
; บ	Copyright (c) 2006 by DataRescue sa/nv,	<ida@datarescue.com>	    บ
; บ			 Licensed to: Freeware version			    บ
; ศอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ
;

; ; Processor:	      D8X
; ; Target assembler: Table Driven Assembler (TASM) by Speech Technology Inc.

; อออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออ

; Segment type:	Pure data
		;.segment FSR
DDRA:		.block 1		; Port A i/o config
DDRB:		.block 1		; Port B i/o config
WDC:		.block 1		; watch	dog timer
TIMER3:		.block 1		; Timer	LSB (bit0~bit2)
TIMER:		.block 1		; Timer	MSB (bit11~bit18)
TIMERL:		.block 1		; Timer	LSB (bit3~bit10)
SIDR_SODR:	.block 1		; DATA XREF: sub_8050+6w
					; Serial Input/Output Data Register
SMRC_SIR:	.block 1		; DATA XREF: __RESET+7r
					; Serial Master	Register Control
CPR0:		.block 1		; Timer	comparison #0 MSB
CPR0L:		.block 1		; Timer	comparison #0 LSB
CPR1:		.block 1		; Timer	comparison #1 MSB
CPR1L:		.block 1		; Timer	comparison #1 LSB
CPR2:		.block 1		; Timer	comparison #2 MSB
CPR2L:		.block 1		; Timer	comparison #2 LSB
CPR3:		.block 1		; Timer	comparison #3 MSB
CPR3L:		.block 1		; Timer	comparison #3 LSB
ASR0P:		.block 1		; ASR0 pos edge	counter	value MSB
ASR0PL:		.block 1		; ASR0 pos edge	counter	value LSB
ASR0N:		.block 1		; ASR0 neg edge	counter	value MSB
ASR0NL:		.block 1		; ASR0 neg edge	counter	value LSB
ASR1P:		.block 1		; ASR1 pos edge	counter	value MSB
ASR1PL:		.block 1		; ASR1 pos edge	counter	value LSB
ASR1N:		.block 1		; ASR1 neg edge	counter	value MSB
ASR1NL:		.block 1		; ASR1 neg edge	counter	value LSB
ASR2:		.block 1		; ASR2 edge counter value MSB
ASR2L:		.block 1		; ASR2 edge counter value LSB
ASR3:		.block 1		; ASR3 edge counter value MSB
ASR3L:		.block 1		; ASR3 edge counter value LSB
		.block 1
		.block 1
		.block 1
OMODE:		.block 1		; DATA XREF: __RESETr
					; Mode control Register
PORTA:		.block 1		; Port A Data Register
PORTAL:		.block 1		; Port A Latch
PORTB:		.block 1		; Port B Data Register
PBCS:		.block 1		; Port B Control Register
TAIT:		.block 1		; Timer	ASR Control
LDOUT:		.block 1		; Latch	DOUT
DOUT:		.block 1		; DOUT Data Register
DOM:		.block 1		; DOUT Control Register
PORTC:		.block 1		; Port C Data Register
PORTD_ASRIN:	.block 1		; Port D Data Register / ASR Input Data
RAMST:		.block 1		; Built-in RAM status
SSD:		.block 1		; DATA XREF: sub_8050r
					; Serial Status	Data Register
IRQL:		.block 1		; Interrupt Request Flag MSB
IRQLL:		.block 1		; Interrupt Request Flag LSB
IMASK:		.block 1		; Interrupt Request Mask MSB
IMASKL:		.block 1		; Interrupt Request Mask LSB
		.block 1
		.block 1
		.block 1
		.block 1
		.block 1
		.block 1
		.block 1
		.block 1
CPR4:		.block 1		; Timer	comparison #0 MSB
CPR4L:		.block 1		; Timer	comparison #0 LSB
CPR5:		.block 1		; Timer	comparison #1 MSB
CPR5L:		.block 1		; Timer	comparison #1 LSB
CPR6:		.block 1		; Timer	comparison #2 MSB
CPR6L:		.block 1		; Timer	comparison #2 LSB
CPR7:		.block 1		; Timer	comparison #3 MSB
CPR7L:		.block 1		; Timer	comparison #3 LSB
; end of 'FSR'

; อออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออ

		.org 40h
srec_checksum:	.block 1
srec_count	.block 2

		.org 8000h
__RESET:	
		; map in internal ROM over external ROM
		ld	#06h, OMODE
		
		; make sure interrupts are disabled
		di
		
		; set stack pointer
		ld	s, #01BFh

		; configure UART for 9600, 8N1
		ld	#18h, SMRC_SIR				; Serial Master	Register Control
		ld	#3Bh, TAIT				; Set watchdog timer rate

		; turn LEDs off
		ld	#00h, DOM
		ld	#0ffh, DOUT                        

		ld	a, #0Dh
		jsr	put_char
		ld	a, #0Ah
		jsr	put_char

		ld	y, #0c000h
		
		jsr	srec_s0
		
		ld	d, #00h
		st	d, srec_count
srec_loop:	jsr	srec_s1
		ld	d, srec_count
		st	b, DOUT
		mov	y, d
		cmpz	a
		bne	srec_loop
		
		jsr	srec_s5
		jsr	srec_s9		

stop:		jmp	stop


srec_s0:	ld	a, #'S'
		jsr	put_char
		ld	a, #'0'
		jsr 	put_char
		
		; clear checksum
		ld	a, #00h
		st	a, srec_checksum
		
		; output length
		ld	a, #05h
		jsr	srec_put_byte

		;output address
		ld	a, #00h
		jsr	srec_put_byte
		ld	a, #00h
		jsr	srec_put_byte

		; output ROM SW ID		
		ld	d, 0FFDCh
		push	b
		jsr	srec_put_byte
		pull	a
		jsr	srec_put_byte
		
		jmp	srec_put_checksum

		
srec_s1:	ld	a, #'S'
		jsr 	put_char
		ld	a, #'1'
		jsr 	put_char
		
		; clear checksum
		ld	a, #00h
		st	a, srec_checksum
		
		; output length
		ld	a, #23h
		jsr	srec_put_byte
		
		; output 2 byte address
		push	y
		mov	y, d		
		push	b
		jsr	srec_put_byte
		pull	a
		jsr	srec_put_byte
		pull	y

		; output 32 bytes
srec_s1_loop:	ld	a, [y]
		jsr	srec_put_byte
		mov	y, d
		and	b, #1fh
		bne	srec_s1_loop
		
		ld	d, srec_count
		add	d, #01h
		st	d, srec_count

		jmp	srec_put_checksum

				
		; output S5 record
srec_s5:	ld	a, #'S'
		jsr 	put_char
		ld	a, #'5'
		jsr 	put_char

		; clear checksum
		ld	a, #00h
		st	a, srec_checksum
	
		; output length
		ld	a, #03h
		jsr	srec_put_byte

		;output number of records
		ld	d, srec_count
		push	b
		jsr	srec_put_byte
		pull	a
		jsr	srec_put_byte
		
		jmp	srec_put_checksum

srec_s9:	ld	a, #'S'
		jsr 	put_char
		ld	a, #'9'
		jsr 	put_char

		; clear checksum
		ld	a, #00h
		st	a, srec_checksum
	
		; output length
		ld	a, #03h
		jsr	srec_put_byte

		;output address
		ld	a, 0fffeh
		jsr	srec_put_byte
		ld	a, 0ffffh
		jsr	srec_put_byte
		
		jmp	srec_put_checksum
					


srec_put_checksum:
		ld	a, srec_checksum
		xor	a, #0ffh
		jsr	srec_put_byte
		ld	a, #0Dh
		jsr	put_char
		ld	a, #0Ah
		jmp	put_char

srec_put_byte:	
		push	a
		ld 	b, srec_checksum
		add	a, b
		st	a, srec_checksum
		pull	a
		jmp	put_hex_byte

put_char:	ld	b, SSD
		and	b, #20h
		beq	put_char
		st	a, SIDR_SODR
		ret

put_str:	ld	a, [y]
		cmpz	a
		beq	put_str_exit
		jsr	put_char
		jmp	put_str
put_str_exit:	ret


; ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ S U B	R O U T	I N E ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ


put_hex_byte:	push 	y
		push	a
		shr	a
		shr	a
		shr	a
		shr	a
		ld	y, #hex_digits
		add	y, a
		ld	a, [y]
		jsr	put_char
		pull 	a		
		and	a, #0Fh
		ld	y, #hex_digits
		add	y, a
		ld	a, [y]
		jsr	put_char
		pull 	y
		ret

; ฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤ
aToshiba8xPromR:.db 0Dh			; DATA XREF: __RESET+Ao
		.db 0Ah
		.text "Toshiba 8X PROM Reader v1.0 Full."
		.db 0Dh
		.db 0Ah
		.text "Copyright(C)2008 Kashi-JBH"
		.db 0Dh
		.db 0Ah
		.db 0

hex_digits:	.db  30h, 31h, 32h, 33h, 34h, 35h, 36h, 37h
		.db  38h, 39h, 41h, 42h, 43h, 44h, 45h, 46h

aDone_:		.db 0Dh			; DATA XREF: __RESET+40o
		.db 0Ah
		.text "done."
		.db 0Dh
		.db 0Ah
		.db 0

		.org 0ffdeh
		
IV0:		.dw 0FFFFh		; External interrupt 0
IV1:		.dw 0FFFFh		; External interrupt 1
IV2:		.dw 0FFFFh		; External interrupt 2
IV3:		.dw 0FFFFh		; External interrupt 3
IV4:		.dw 0FFFFh		; External interrupt 4
IV5:		.dw 0FFFFh		; External interrupt 5
IV6:		.dw 0FFFFh		; External interrupt 6
IV7:		.dw 0FFFFh		; External interrupt 7
IV8:		.dw 0FFFFh		; External interrupt 8
IV9:		.dw 0FFFFh		; External interrupt 9
IVa:		.dw 0FFFFh		; External interrupt a
IVb:		.dw 0FFFFh		; External interrupt b
IVc:		.dw 0FFFFh		; External interrupt c
IVd:		.dw 0FFFFh		; External interrupt d
IVe:		.dw 0FFFFh		; External interrupt e
IVf:		.dw 0FFFFh		; External interrupt f
		.dw __RESET		; Processor reset
; end of 'ROM'


		.end
