/*
 * dash_splash.h
 *
 * The power-on splash images. The table is src/dash_splash.c, GENERATED by
 * tools/splash/build_splash.py from the pictures in hw/dash_cluster/art -
 * rerun that rather than editing it.
 *
 * Each image is a rectangle of 8-bit indices into a palette of its own. The
 * splash is the only thing on the glass while it runs, so it does not share
 * the gauges' palette: the chrome emblem gets every grey it needs, and a
 * letter a ramp from black to the gauges' white. Palettes are RGB triples, not
 * panel words, because the fade scales them afresh every frame.
 *
 * Every rectangle is on even coordinates with an even size - the panel takes
 * its window in 2-pixel units - and index 0 is always exact black, the colour
 * of everything around it.
 */
#ifndef DASH_SPLASH_H_
#define DASH_SPLASH_H_

#include <stdint.h>

typedef struct
{
	int32_t X, Y;			/* top left on the panel */
	int32_t Width, Height;
	const uint8_t *Data;		/* Width x Height indices, row by row */
	const uint8_t *Palette;		/* PaletteCount RGB triples */
	uint16_t PaletteCount;
} DashSplashImage_t;

extern const DashSplashImage_t DashSplashEmblem;
extern const DashSplashImage_t DashSplashLetterM;
extern const DashSplashImage_t DashSplashLetterR;
extern const DashSplashImage_t DashSplashLetter2;

#endif /* DASH_SPLASH_H_ */
