/*
 * dash_faces.h
 *
 * The pre-rendered gauge dials. The table itself is src/dash_faces.c, which is
 * GENERATED by tools/face_render/build_faces.py - rerun that after changing a
 * gauge's ticks, placement or ui_gauge.c, rather than editing it.
 */
#ifndef DASH_FACES_H_
#define DASH_FACES_H_

#include <stdint.h>

#include "lvgl.h"

typedef struct
{
	uint8_t Page;			/* index into Pages[] */
	uint8_t Element;		/* index into that page's Elements[] */
	int32_t Width;			/* the element size it was rendered for, so a */
	int32_t Height;			/* face that no longer fits can be refused */
	const lv_image_dsc_t *Image;	/* RGB565_SWAPPED, the panel's own byte order */
} DashFace_t;

extern const DashFace_t DashFaces[];
extern const uint8_t DashFaceCount;

#endif /* DASH_FACES_H_ */
