/*
 * dash_faces.h
 *
 * The pre-rendered gauge dials. The table itself is src/dash_faces.c, which is
 * GENERATED by tools/face_render/build_faces.py - rerun that after changing a
 * gauge's ticks, placement or ui_gauge.c, rather than editing it.
 *
 * PALETTED ON THE PC, NOT ON THE NODE.
 *
 * Each face is one byte per pixel, indexing DashFacePalette - a single table
 * shared by every face, so any of them can be copied into the back buffer as
 * it stands. The generator builds the table from every colour the renderer
 * produced, so nothing is quantised, and it checks that each face decodes back
 * to the renderer's exact RGB565 before writing it. It refuses outright if the
 * faces ever need more than DASH_FACE_PALETTE_SIZE colours between them.
 */
#ifndef DASH_FACES_H_
#define DASH_FACES_H_

#include <stdint.h>

#define DASH_FACE_PALETTE_SIZE	(256u)

typedef struct
{
	int32_t Width;
	int32_t Height;
	uint32_t Stride;		/* bytes per row - one per pixel */
	const uint8_t *Data;		/* indices into DashFacePalette */
} DashImage_t;

typedef struct
{
	uint8_t Page;			/* index into Pages[] */
	uint8_t View;			/* 0 the page's own view, 1 its alternative */
	uint8_t Element;		/* index into that view's elements */
	int32_t Width;			/* the element size it was rendered for, so a */
	int32_t Height;			/* face that no longer fits can be refused */
	const DashImage_t *Image;
} DashFace_t;

extern const DashFace_t DashFaces[];
extern const uint8_t DashFaceCount;

/* RGB565 in the panel's byte order once stored: each entry, written to memory
   little-endian, gives the two bytes high first. Index 0 is always black, and
   entries past DashFacePaletteUsed are black and free - which is where the
   colours drawn live, the needle's among them, will go. */
extern const uint16_t DashFacePalette[DASH_FACE_PALETTE_SIZE];
extern const uint16_t DashFacePaletteUsed;

#endif /* DASH_FACES_H_ */
