/*
 * ui_lvgl.c
 *
 * The LVGL binding: page tables in, LVGL objects out.
 *
 * Deliberately mechanical. Every judgement - staleness, warning bands, needle
 * position, what to show before any data arrives - is made in ui_model.c,
 * which builds and is tested on a host. This file only translates that into
 * lv_arc/lv_label/lv_bar/lv_chart calls, so it can be read and confirmed by
 * eye without a panel attached.
 *
 * LVGL 8.x. The vendor's CO5300 panel driver and CST9217 touch glue are
 * written against 8.1, so that is the version to match until someone
 * deliberately ports both - see PLAN.md section 4.1a.
 *
 * The hardware-specific parts - the flush callback and the touch read - are
 * in panel.c, which is the only file that knows a CO5300 or a CST9217 exists.
 * Nothing here refers to either.
 */

#include <stdio.h>
#include <string.h>

#include "lvgl.h"

#include "dash_faces.h"
#include "pages.h"
#include "signals.h"
#include "panel.h"
#include "ui_gauge.h"
#include "ui_lvgl.h"
#include "ui_model.h"

/* The gauge value readout. Montserrat, like the tick labels, but with tabular
   digits: every digit has the same advance, so a changing reading does not
   shuffle sideways the way a proportional centred label does. Generated by
   tools/gen_font.py - regenerate it, do not edit it. */
LV_FONT_DECLARE(dash_font_value_56);

/* The unit under a gauge's value, in the dial's legend face. */
LV_FONT_DECLARE(dash_font_legend_26);

/* Vertical space between a gauge's value and the unit printed under it. */
#define UI_GAUGE_UNIT_GAP	(6)

/* One LVGL object per element of the current page, rebuilt on a page change
   and only updated in between. Rebuilding every frame would allocate and free
   continuously on a node with no heap to spare. */
#define UI_MAX_ELEMENTS		(8)

/* Enough for the longest formatted value plus its unit - Signal_Format() is
   bounded well under this. */
#define UI_TEXT_MAX		(24)

/* How often a graph advances. A chart is a time series and has to move whether
   or not the reading changed, so it is the one widget that cannot be skipped
   when nothing happens - which makes its cadence a real cost. At 100 points
   this gives ten seconds of history; driving it every 20 ms gave two, and
   redrew five times as often for the privilege. */
#define UI_CHART_PERIOD_MS	(100u)

/* How often a value readout's text is redrawn. The needle moves on every frame;
   the number does not need to. Digits changing sixty times a second cannot be
   read anyway, and redrawing them was the largest cost left in a frame - the
   56 px glyphs plus the face copied out of flash behind them - which put a
   frame over the 16.8 ms scan often enough to miss about one scan in nine. Ten
   updates a second still reads as live. A change of state - a gauge going
   stale, or data arriving - is shown at once, not held for the next tick. */
#define UI_VALUE_PERIOD_MS	(100u)

typedef struct
{
	lv_obj_t *Object;	/* the scale, arc, bar or label itself */
	lv_obj_t *Value;	/* the value text, where the widget has one */
	lv_obj_t *Unit;		/* WIDGET_GAUGE only: the unit, apart from the value */
	lv_obj_t *Label;	/* the signal name */
	lv_obj_t *Needle;	/* WIDGET_GAUGE only: the line that swings */
	int32_t NeedleLen;	/* pixels from the pivot to the tip, fixed at build */
	int32_t NeedleInner;	/* pixels from the pivot to where the needle starts */
	int32_t NeedleCx;	/* pivot, in the scale's own coordinates */
	int32_t NeedleCy;

	/* What was last pushed into LVGL, so an unchanged gauge costs nothing.
	   See the note at the top of UiLvgl_Update(). */
	bool Primed;		/* false until every property has been pushed once */
	uint16_t LastPosition;

	/* WIDGET_GAUGE only: the eased needle position, UI_NEEDLE_Q fractional
	   bits, and the endpoints last drawn - a needle is only re-sent to LVGL
	   when a pixel of it would actually move. */
	uint32_t SmoothQ;
	int32_t LastIx, LastIy, LastTx, LastTy;
	UiState_t LastState;
	const char *LastLabel;
	const char *LastUnit;
	char LastText[UI_TEXT_MAX];

	uint32_t NextChartMs;
	uint32_t NextTextMs;	/* when the value text may next be redrawn */
} UiObject_t;

static lv_obj_t *Screen;
static UiObject_t Objects[UI_MAX_ELEMENTS];
static uint8_t ObjectCount;
static uint8_t BuiltPage = 0xFF;

/* How the next page change should be presented, set by the gesture that caused
   it and consumed by the rebuild. A change nobody swiped for - the fault
   takeover - stays LV_SCREEN_LOAD_ANIM_NONE deliberately: a warning that slides
   in gently is a warning the driver reads late. */
static lv_screen_load_anim_t PendingAnim = LV_SCREEN_LOAD_ANIM_NONE;

/* Long enough to read as movement, short enough not to feel like waiting.
   Both screens are drawn for this long, so it is also the only moment the
   renderer has two object trees and twice the draw area.

   200 ms read as too fast on the glass, then 350 ms still did. A full-screen
   redraw is the most expensive thing this renderer does, so a short slide is
   also a slide made of very few steps - lengthening it helps twice over. At
   600 ms and roughly 30 frames a second this is about eighteen steps across
   the travel. */
#define UI_TRANSITION_MS	(400u)

/* A CROSSFADE, BECAUSE MOTION CANNOT BE MADE SMOOTH HERE.
 *
 * Three sliding transitions were tried on the glass and all three looked bad,
 * for one reason that no amount of tuning fixes. A full-screen frame costs
 * about 30 ms out of LVGL's software renderer - no 2D acceleration on this
 * part - so 466 pixels of travel is roughly twenty steps of twenty-three
 * pixels. The eye tracks moving content and reads those steps as judder.
 * Shortening the transition gives fewer, bigger steps; lengthening it just
 * prolongs the experience.
 *
 * A fade has nothing to track. The same ten or twenty frames that look
 * stuttery as motion read as a smooth dissolve as brightness, because there
 * are no edges moving across the retina. It costs the same per frame as the
 * slide did - both screens are composited while the new one is part
 * transparent - and looks better for it.
 *
 * What was tried, so nobody repeats it: MOVE (both faces animate) at 350 and
 * 600 ms, OVER (only the incoming face animates, half the per-frame cost) at
 * 600 ms, and a strip-by-strip wipe. The wipe was the cheapest by far - it
 * renders each face exactly once, where a slide renders the moving one every
 * frame - and was rejected on looks, which is the right criterion for an
 * animation.
 *
 * The honest cost of a fade: it has no direction, so a leftward and a
 * rightward swipe look identical and the driver gets no cue which way the
 * carousel moved. The face's own name is the cue instead.
 *
 * If motion is ever wanted for real, the only thing that would work is
 * snapshotting each face once into an 8bpp framebuffer and compositing rows
 * from two of them straight to the panel - around 6 ms a frame, so genuinely
 * 60 fps. It costs 424 KB of the 520 KB SRAM and RGB332 colour, and it lives
 * outside LVGL. Measured numbers behind all of this are in the git history
 * around this commit. */
#define UI_ANIM_PAGE_CHANGE	LV_SCREEN_LOAD_ANIM_FADE_IN

/* Gestures are ignored until this time. Two reasons, and the second is the
   real one: a second swipe mid-transition would ask LVGL to load a third
   screen while the previous one is still being animated out and deleted, and
   on a dashboard a swipe that lands twice is worse than one that is briefly
   ignored. */
static uint32_t TransitionUntilMs;

/* Percent of the panel to pixels. The page tables are in percent so one table
   serves the 1.43" and 1.75" panels, which share 466x466. */
static void UiLvgl_GestureEvent(lv_event_t *Event);

static int32_t Pct(uint8_t Percent, int32_t Extent)
{
	return UiGauge_Pct(Percent, Extent);
}


/***************************************************************************************/
/* The sweep, start angle and tick spacing live in ui_gauge.h, shared with the
   face renderer - the needle has to land on graduations that were drawn on a
   PC. */

/* Needle length as a percent of the gauge's radius. Long enough to reach in
   among the tick labels. */
#define UI_GAUGE_NEEDLE_PCT	(85)

/* Where the needle starts, and its stroke width, live in ui_gauge.h: the ring
   baked into the face is sized to meet the needle's inner end exactly.

   Space kept round the needle inside its line object, so the rounded end caps
   of the stroke stay within the area that gets invalidated. */
#define UI_GAUGE_NEEDLE_PAD	(4)


/***************************************************************************************/
static void UiLvgl_NeedleDeleted(lv_event_t *Event)
{
	lv_free(lv_event_get_user_data(Event));
}


/***************************************************************************************/
/* Point the needle, keeping its line object wrapped tightly round it.
 *
 * This is not lv_scale_set_line_needle_value(), and the reason is tearing.
 * That function leaves the line object at the scale's top-left corner with
 * its first point at the centre, and an lv_line sizes itself from its own
 * origin out to its furthest point - so the object, and therefore everything
 * invalidated when the needle moves, is a square from the corner of the dial
 * out to the tip. Measured on the glass, frames were exactly 230 x 230 and
 * 347 x 347 pixels: up to ~150k px repainted to move a 5 px line, rendered in
 * 60-line bands over ~45 ms, and the panel scanning out a half-written needle
 * part way through.
 *
 * Positioning the object at the needle's own bounding box, with the points
 * relative to it, brings a frame down to the region the needle actually swept
 * - a few tens of thousands of pixels, small enough to render whole and send
 * as one burst. See PANEL_BUF_LINES in panel.c for the other half.
 */
static void UiLvgl_SetNeedle(UiObject_t *O, uint32_t PositionQ, bool Force)
{
	lv_point_precise_t *P = lv_line_get_points_mutable(O->Needle);

	/* The angle to a 256th of a degree, not a whole one. LVGL's sine table is
	   in whole degrees, and a whole degree is a ~3 px jump at the tip - 270
	   steps across the dial, which no amount of easing can hide - so the ray
	   is interpolated between the two degrees either side. Over one degree the
	   error of doing that linearly is far below a pixel. */
	uint32_t AngleQ = (uint32_t)(((uint64_t)UI_GAUGE_ANGLE_RANGE * PositionQ)
	                             / (uint32_t)UI_POSITION_MAX);
	int16_t Deg = (int16_t)(UI_GAUGE_ROTATION + (int32_t)(AngleQ >> UI_NEEDLE_Q));
	int32_t Frac = (int32_t)(AngleQ & ((1u << UI_NEEDLE_Q) - 1u));
	int32_t Cos0 = lv_trigo_cos(Deg);
	int32_t Sin0 = lv_trigo_sin(Deg);
	int32_t Cos = Cos0 + (((lv_trigo_cos((int16_t)(Deg + 1)) - Cos0) * Frac) >> UI_NEEDLE_Q);
	int32_t Sin = Sin0 + (((lv_trigo_sin((int16_t)(Deg + 1)) - Sin0) * Frac) >> UI_NEEDLE_Q);
	const int32_t Half = (int32_t)1 << (LV_TRIGO_SHIFT - 1);

	/* Both ends lie on the same ray from the pivot: the inner end at
	   NeedleInner, the tip at NeedleLen. Rounded to the nearest pixel rather
	   than truncated, which biased every endpoint up and to the left. The
	   pivot itself is not drawn, so the middle of the dial stays empty - and
	   the bounding box never has to reach the centre. */
	int32_t Ix = O->NeedleCx + ((O->NeedleInner * Cos + Half) >> LV_TRIGO_SHIFT);
	int32_t Iy = O->NeedleCy + ((O->NeedleInner * Sin + Half) >> LV_TRIGO_SHIFT);
	int32_t Tx = O->NeedleCx + ((O->NeedleLen * Cos + Half) >> LV_TRIGO_SHIFT);
	int32_t Ty = O->NeedleCy + ((O->NeedleLen * Sin + Half) >> LV_TRIGO_SHIFT);
	int32_t MinX, MinY, MaxX, MaxY;

	/* Nothing to send if no pixel moves - the eased position changes on every
	   frame, but near its target by less than a pixel. */
	if (!Force && Ix == O->LastIx && Iy == O->LastIy && Tx == O->LastTx && Ty == O->LastTy)
		return;
	O->LastIx = Ix;
	O->LastIy = Iy;
	O->LastTx = Tx;
	O->LastTy = Ty;

	MinX = LV_MIN(Ix, Tx) - UI_GAUGE_NEEDLE_PAD;
	MinY = LV_MIN(Iy, Ty) - UI_GAUGE_NEEDLE_PAD;
	MaxX = LV_MAX(Ix, Tx) + UI_GAUGE_NEEDLE_PAD;
	MaxY = LV_MAX(Iy, Ty) + UI_GAUGE_NEEDLE_PAD;

	/* Tell the panel where the needle is moving through - where it was and
	   where it is going, in screen coordinates - so whichever flush repaints
	   that waits for TE. The parent is a padless image or scale, so its
	   content area starts at its own corner. */
	{
		lv_area_t Parent;
		lv_area_t Old;

		lv_obj_get_coords(O->Object, &Parent);
		lv_obj_get_coords(O->Needle, &Old);
		Panel_SyncArea(LV_MIN(Old.x1, Parent.x1 + MinX),
		               LV_MIN(Old.y1, Parent.y1 + MinY),
		               LV_MAX(Old.x2, Parent.x1 + MaxX),
		               LV_MAX(Old.y2, Parent.y1 + MaxY));
	}

	P[0].x = Ix - MinX;
	P[0].y = Iy - MinY;
	P[1].x = Tx - MinX;
	P[1].y = Ty - MinY;

	/* An explicit size rather than LVGL's content sizing, which runs from the
	   object's origin to the furthest point and would leave the far end cap
	   outside the invalidated area. */
	lv_obj_set_pos(O->Needle, MinX, MinY);
	lv_obj_set_size(O->Needle, MaxX - MinX + 1, MaxY - MinY + 1);
	lv_line_set_points_mutable(O->Needle, P, 2);
}


/***************************************************************************************/
/* A bare black screen, ready to have a face built on it.
 *
 * One per page rather than one reused, because lv_screen_load_anim() animates
 * between two screens - there is nothing to slide if both faces live on the
 * same one. The old screen is deleted by the load, so only two exist at once
 * and only for UI_TRANSITION_MS. */
static lv_obj_t *UiLvgl_MakeScreen(void)
{
	lv_obj_t *New = lv_obj_create(NULL);

	/* The theme styles a plain object like a card - a light panel, a border and
	   padding. On a round AMOLED in a dashboard the background must be true
	   black, both because anything else is a visible disc and because black
	   costs an AMOLED no light. */
	lv_obj_set_style_bg_color(New, lv_color_black(), LV_PART_MAIN);
	lv_obj_set_style_bg_opa(New, LV_OPA_COVER, LV_PART_MAIN);
	lv_obj_set_style_border_width(New, 0, LV_PART_MAIN);
	lv_obj_set_style_pad_all(New, 0, LV_PART_MAIN);
	lv_obj_set_style_radius(New, 0, LV_PART_MAIN);

	/* See the note in UiLvgl_BuildElement(): a scroll in progress suppresses
	   gesture detection outright, and LVGL creates everything scrollable. */
	lv_obj_remove_flag(New, LV_OBJ_FLAG_SCROLLABLE);

	/* EVERY screen needs this, not just the first. The gesture lands on the
	   screen because LVGL walks up from the object under the finger while each
	   one has LV_OBJ_FLAG_GESTURE_BUBBLE - default on for children, off for a
	   screen - so the walk stops here. Miss it on a new screen and swiping
	   works exactly once. */
	lv_obj_add_event_cb(New, UiLvgl_GestureEvent, LV_EVENT_GESTURE, NULL);

	return New;
}


/***************************************************************************************/
static void UiLvgl_Style(lv_obj_t *Object, UiState_t State)
{
	lv_color_t Colour;

	switch (State)
	{
	case UI_STATE_WARNING:
		Colour = lv_palette_main(LV_PALETTE_RED);
		break;
	case UI_STATE_STALE:
	case UI_STATE_NODATA:
		/* Dimmed rather than hidden. A driver must be able to see that a gauge
		   exists and is not reporting, which is different from a gauge that is
		   not there. */
		Colour = lv_palette_darken(LV_PALETTE_GREY, 2);
		break;
	case UI_STATE_NORMAL:
	default:
		Colour = lv_color_white();
		break;
	}

	lv_obj_set_style_text_color(Object, Colour, LV_PART_MAIN);
	lv_obj_set_style_arc_color(Object, Colour, LV_PART_INDICATOR);
	lv_obj_set_style_bg_color(Object, Colour, LV_PART_INDICATOR);

	/* A scale's ticks and numbers are its MAIN and ITEMS parts, so the state
	   colour has to reach those too or a stale gauge would keep bright white
	   graduations around a dimmed needle. */
	lv_obj_set_style_line_color(Object, Colour, LV_PART_MAIN);
	lv_obj_set_style_line_color(Object, Colour, LV_PART_ITEMS);
	lv_obj_set_style_text_color(Object, Colour, LV_PART_INDICATOR);
}


/***************************************************************************************/
/* The pre-rendered dial for a gauge, or NULL. Matched on the element's address
   in Pages[], and refused if the face was rendered for a different size - a
   stretched or cropped dial would put the graduations somewhere the needle is
   not. A face with outdated tick labels cannot be detected here; see
   build_faces.py. */
static const lv_image_dsc_t *UiLvgl_FindFace(const FaceElement_t *Element,
                                             int32_t W, int32_t H)
{
	uint8_t i;

	for (i = 0; i < DashFaceCount; i++)
	{
		const DashFace_t *F = &DashFaces[i];

		if (F->Page >= PageCount || F->Element >= Pages[F->Page].ElementCount)
			continue;
		if (&Pages[F->Page].Elements[F->Element] != Element)
			continue;
		if (F->Width != W || F->Height != H)
			return NULL;
		return F->Image;
	}
	return NULL;
}


/***************************************************************************************/
static void UiLvgl_BuildElement(const FaceElement_t *Element, UiObject_t *Out,
                                int32_t W, int32_t H)
{
	int32_t X = Pct(Element->X, W);
	int32_t Y = Pct(Element->Y, H);
	int32_t EW = Pct(Element->W, W);
	int32_t EH = Pct(Element->H, H);

	/* EVERY FIELD IS SEEDED BEFORE THE WIDGET IS BUILT, NOT AFTER.
	 *
	 * This block used to sit after the switch below, and it reset Needle to
	 * NULL straight after lv_line_create() had filled it in - so every gauge
	 * then asked LVGL to position a NULL needle. LVGL did not fault on it:
	 * LV_USE_ASSERT_OBJ was off, and low memory on RP2350 is readable boot
	 * ROM, so it read garbage there and passed it to lv_realloc(). The first
	 * sign of anything wrong was TLSF reporting "block already marked as free",
	 * three calls away from the cause. Order matters here; keep it first.
	 *
	 * Nothing has been pushed into this object yet, so the first update writes
	 * every property regardless of what it compares against - cheaper and far
	 * clearer than seeding each cache with a value the model cannot produce. */
	Out->Object = NULL;
	Out->Value = NULL;
	Out->Unit = NULL;
	Out->Label = NULL;
	Out->Needle = NULL;
	Out->NeedleLen = 0;
	Out->NeedleInner = 0;
	Out->NeedleCx = 0;
	Out->NeedleCy = 0;
	Out->Primed = false;
	Out->LastPosition = 0;
	Out->SmoothQ = 0;
	Out->LastIx = Out->LastIy = Out->LastTx = Out->LastTy = 0;
	Out->LastState = UI_STATE_NORMAL;
	Out->LastLabel = NULL;
	Out->LastUnit = NULL;
	Out->LastText[0] = '\0';
	Out->NextChartMs = 0;
	Out->NextTextMs = 0;

	switch (Element->Type)
	{
	case WIDGET_GAUGE:
	{
		/* THE DIAL IS A PICTURE.
		 *
		 * Its graduations and numbers never change, so they are rendered once
		 * on the PC by tools/face_render - LVGL's own lv_scale, same config,
		 * same fonts - and shown here as an image. Measured on the board,
		 * drawing that scale live cost about two thirds of every frame: it
		 * regenerates all 41 ticks and 9 labels for every redrawn area, even
		 * one in the empty middle of the dial that contains none of them. An
		 * image in the panel's own byte order costs a copy of the pixels
		 * actually under the redraw.
		 *
		 * The needle is still an ordinary line positioned by
		 * UiLvgl_SetNeedle(), so it has to agree with the picture - which is
		 * why the sweep and start angle come from ui_gauge.h. */
		const lv_image_dsc_t *Face = UiLvgl_FindFace(Element, EW, EH);
		int32_t Radius;

		if (Face != NULL)
		{
			Out->Object = lv_image_create(Screen);
			lv_image_set_src(Out->Object, Face);
			lv_obj_set_pos(Out->Object, X, Y);
			lv_obj_set_size(Out->Object, EW, EH);
		}
		else
		{
			/* Draw it live rather than show a gauge with no graduations. Slow,
			   and said so, because it means the faces need regenerating. */
			LV_LOG_WARN("no pre-rendered face fits this gauge - run "
			            "tools/face_render/build_faces.py; drawing the scale live");
			Out->Object = UiGauge_CreateScale(Screen, Element, X, Y, EW, EH);
		}

		Radius = UiGauge_Radius(EW, EH);
		Out->NeedleLen = (Radius * UI_GAUGE_NEEDLE_PCT) / 100;
		Out->NeedleInner = UiGauge_NeedleInner(EW, EH);
		Out->NeedleCx = EW / 2;
		Out->NeedleCy = EH / 2;

		Out->Needle = lv_line_create(Out->Object);

		/* The line keeps a pointer to its points rather than a copy, so they
		   need storage that lives exactly as long as the line. Not a slot in
		   Objects[]: that is reused as soon as the next face is built, while
		   the outgoing face is still on the glass for the length of the
		   crossfade and would draw its needle from the new face's numbers. */
		{
			lv_point_precise_t *Points =
				lv_malloc_zeroed(2u * sizeof(lv_point_precise_t));

			LV_ASSERT_MALLOC(Points);
			lv_line_set_points_mutable(Out->Needle, Points, 2);
			lv_obj_add_event_cb(Out->Needle, UiLvgl_NeedleDeleted,
			                    LV_EVENT_DELETE, Points);
		}

		lv_obj_set_style_line_width(Out->Needle, UI_GAUGE_NEEDLE_WIDTH,
		                            LV_PART_MAIN);
		lv_obj_set_style_line_rounded(Out->Needle, true, LV_PART_MAIN);
		lv_obj_set_style_line_color(Out->Needle,
		                            lv_color_hex(UI_GAUGE_NEEDLE_COLOUR),
		                            LV_PART_MAIN);
		break;
	}

	case WIDGET_DIAL:
	case WIDGET_ARC:
		Out->Object = lv_arc_create(Screen);
		lv_obj_set_pos(Out->Object, X, Y);
		lv_obj_set_size(Out->Object, EW, EH);
		lv_arc_set_range(Out->Object, 0, UI_POSITION_MAX);
		/* A dial sweeps most of the circle; an arc is a shallower indicator
		   used as a secondary reading on the same face. */
		if (Element->Type == WIDGET_DIAL)
			lv_arc_set_bg_angles(Out->Object, 135, 45);
		else
			lv_arc_set_bg_angles(Out->Object, 160, 20);
		lv_obj_remove_style(Out->Object, NULL, LV_PART_KNOB);
		lv_obj_remove_flag(Out->Object, LV_OBJ_FLAG_CLICKABLE);
		break;

	case WIDGET_BARGRAPH:
		Out->Object = lv_bar_create(Screen);
		lv_obj_set_pos(Out->Object, X, Y);
		lv_obj_set_size(Out->Object, EW, EH);
		lv_bar_set_range(Out->Object, 0, UI_POSITION_MAX);
		break;

	case WIDGET_GRAPH:
		Out->Object = lv_chart_create(Screen);
		lv_obj_set_pos(Out->Object, X, Y);
		lv_obj_set_size(Out->Object, EW, EH);
		lv_chart_set_type(Out->Object, LV_CHART_TYPE_LINE);
		lv_chart_set_range(Out->Object, LV_CHART_AXIS_PRIMARY_Y, 0, UI_POSITION_MAX);
		lv_chart_set_point_count(Out->Object, 100);
		lv_chart_add_series(Out->Object, lv_palette_main(LV_PALETTE_AMBER),
		                    LV_CHART_AXIS_PRIMARY_Y);
		break;

	case WIDGET_NUMERIC:
	default:
		Out->Object = lv_obj_create(Screen);
		lv_obj_set_pos(Out->Object, X, Y);
		lv_obj_set_size(Out->Object, EW, EH);
		lv_obj_set_style_bg_opa(Out->Object, LV_OPA_TRANSP, LV_PART_MAIN);
		lv_obj_set_style_border_width(Out->Object, 0, LV_PART_MAIN);
		break;
	}

	Out->Value = lv_label_create(Out->Object);
	lv_label_set_text(Out->Value, "--");

	if (Element->Type == WIDGET_GAUGE)
	{
		/* A gauge's value lives in the empty middle of the dial, large, with
		   its unit on its own line underneath. Separating the unit is what
		   lets it stay still: printed after the number in one label it rode
		   along with every change in the number's width.

		   The pair is centred as a block, positioned from the two fonts' line
		   heights rather than with lv_obj_align_to(), which places an object
		   once against the other's current size and would not follow the
		   value as its text changes. */
		const lv_font_t *UnitFont = &dash_font_legend_26;
		int32_t ValueH = lv_font_get_line_height(&dash_font_value_56);
		int32_t UnitH = lv_font_get_line_height(UnitFont);
		int32_t BlockH = ValueH + UI_GAUGE_UNIT_GAP + UnitH;

		lv_obj_set_style_text_font(Out->Value, &dash_font_value_56, LV_PART_MAIN);
		lv_obj_align(Out->Value, LV_ALIGN_CENTER, 0, (ValueH - BlockH) / 2);

		Out->Unit = lv_label_create(Out->Object);
		lv_obj_set_style_text_font(Out->Unit, UnitFont, LV_PART_MAIN);
		lv_label_set_text(Out->Unit, "");
		lv_obj_align(Out->Unit, LV_ALIGN_CENTER, 0, (BlockH - UnitH) / 2);
	}
	else
	{
		/* Everything else keeps value and unit in one label, as before - the
		   warning page's boxes have no room for a second line. */
		lv_obj_align(Out->Value, LV_ALIGN_CENTER, 0, 0);
	}

	/* The signal's name, at the foot of the widget - except on a gauge, whose
	   face carries its legend ("x1000r/min") painted in, as the MR2's does. A
	   gauge's state still shows, through its value and unit. */
	if (Element->Type != WIDGET_GAUGE)
	{
		Out->Label = lv_label_create(Out->Object);
		lv_obj_align(Out->Label, LV_ALIGN_BOTTOM_MID, 0, 0);
	}

	/* NOTHING ON A FACE MAY SCROLL.
	 *
	 * LVGL creates every object scrollable, and its gesture detection gives
	 * up the moment a scrollable object under the finger starts scrolling -
	 * indev_gesture() returns early if a scroll is in progress. A widget
	 * whose content sits a pixel outside its bounds is enough to make that
	 * happen, and the symptom is a swipe that sometimes changes page and
	 * sometimes does not. So the flag comes off every widget, and off the
	 * screen itself in UiLvgl_Init().
	 *
	 * Gesture bubbling is left alone: LVGL sets it on every child by default
	 * and walks up to the first ancestor without it, which is the screen. */
	lv_obj_remove_flag(Out->Object, LV_OBJ_FLAG_SCROLLABLE);
}


/***************************************************************************************/
static void UiLvgl_BuildPage(uint8_t Page)
{
	const FacePage_t *Face = &Pages[Page];

	/* From the display, not from the screen object. A screen that has just
	   been created and not yet laid out can report a width of zero, and every
	   element is positioned as a percentage of it - so reading it from the
	   object would collapse the whole face to nothing on exactly the page
	   changes this function exists to handle. */
	int32_t W = lv_display_get_horizontal_resolution(NULL);
	int32_t H = lv_display_get_vertical_resolution(NULL);
	lv_obj_t *New = UiLvgl_MakeScreen();
	uint8_t i;

	ObjectCount = Face->ElementCount;
	if (ObjectCount > UI_MAX_ELEMENTS)
		ObjectCount = UI_MAX_ELEMENTS;

	Screen = New;

	for (i = 0; i < ObjectCount; i++)
		UiLvgl_BuildElement(&Face->Elements[i], &Objects[i], W, H);

	/* auto_del: the screen being replaced is deleted once the animation
	   finishes, which is what keeps this from leaking a face per swipe. Its
	   widgets are still being drawn as they slide away, holding whatever
	   values they last had - correct, since they are leaving. */
	lv_screen_load_anim(New, PendingAnim,
	                 (PendingAnim == LV_SCREEN_LOAD_ANIM_NONE)
	                         ? 0 : (uint32_t)UI_TRANSITION_MS,
	                 0, true);

	if (PendingAnim != LV_SCREEN_LOAD_ANIM_NONE)
		TransitionUntilMs = lv_tick_get() + UI_TRANSITION_MS;

	/* Back to no animation, so a page change from anywhere other than a
	   gesture is instant rather than inheriting the last swipe's direction. */
	PendingAnim = LV_SCREEN_LOAD_ANIM_NONE;

	BuiltPage = Page;
}


/***************************************************************************************/
static void UiLvgl_GestureEvent(lv_event_t *Event)
{
	(void)Event;
	UiLvgl_HandleGesture();
}


/***************************************************************************************/
void UiLvgl_Init(void)
{
	/* Black the screen LVGL made for the display. Nothing is built on it - the
	   first UiLvgl_Update() replaces it with a real face - but it is on the
	   glass until then, and the theme's default is a pale card. */
	lv_obj_set_style_bg_color(lv_screen_active(), lv_color_black(), LV_PART_MAIN);

	Screen = NULL;
	BuiltPage = 0xFF;
	ObjectCount = 0;
	PendingAnim = LV_SCREEN_LOAD_ANIM_NONE;
	TransitionUntilMs = 0;
}


/***************************************************************************************/
/* PUSH ONLY WHAT CHANGED.
 *
 * This ran unconditionally once, and it cost more than everything else in the
 * firmware put together. Measured on the board: a static face with nothing on
 * the bus redrew 187,489 pixels every 60 ms - 433 squared, which is one 90%
 * dial plus its extended draw area, repainted sixteen times a second for no
 * reason at all.
 *
 * LVGL cannot prevent this on its own. lv_arc_set_value() does early-out on an
 * unchanged value, but lv_label_set_text() never compares the string it is
 * handed, and every lv_obj_set_style_*() call invalidates the whole widget -
 * and UiLvgl_Style() makes three of them per element. So the comparison has to
 * happen here.
 *
 * It is worth more than a smoother transition: a dashboard gauge is static
 * most of the time, and a core busy repainting an unchanged dial is a core not
 * available to the renderer during a page change - or, once there is a bus, one
 * competing with can2040 for memory bandwidth.
 */
void UiLvgl_Update(uint32_t NowMs, uint32_t FrameUs)
{
	uint8_t Page = Pages_Effective(NowMs);
	const FacePage_t *Face;
	uint8_t i;

	if (Page != BuiltPage)
		UiLvgl_BuildPage(Page);
	else if ((int32_t)(lv_tick_get() - TransitionUntilMs) < 0)
		/* Mid-slide. New label text invalidates areas on top of the
		   animation's own invalidation, for values nobody can read while the
		   face is moving. Note this is the `else` branch on purpose: the call
		   that builds a page still falls through and populates it, so a face is
		   never shown holding the placeholder text. */
		return;

	Face = &Pages[Page];

	for (i = 0; i < ObjectCount; i++)
	{
		const FaceElement_t *Element = &Face->Elements[i];
		UiObject_t *O = &Objects[i];
		UiWidget_t Widget = UiModel_Widget(Element, NowMs);
		bool Force = !O->Primed;
		char Text[UI_TEXT_MAX];

		/* LVGL takes a signed coordinate; the model produces an unsigned
		   0..UI_POSITION_MAX, which is 1000 - so the cast cannot lose
		   anything, and the ranges set in UiLvgl_BuildElement() match. */
		int32_t Position = (int32_t)Widget.Position;

		switch (Element->Type)
		{
		case WIDGET_GAUGE:
			/* No NULL guard here, deliberately. One was added while chasing
			   the needle fault and it is what hid it: silently skipping a
			   NULL needle made "never drawn" look like a working build.
			   LV_USE_ASSERT_OBJ catches a NULL object loudly instead - in a
			   debug build; it is off in release, see lv_conf.h. */
			/* Eased towards the reading on every frame; see
			   UiModel_NeedleStep(). A freshly built face starts on its
			   reading rather than swinging up from zero. */
			O->SmoothQ = Force ? ((uint32_t)Widget.Position << UI_NEEDLE_Q)
			                   : UiModel_NeedleStep(O->SmoothQ, Widget.Position, FrameUs);
			UiLvgl_SetNeedle(O, O->SmoothQ, Force);
			break;
		case WIDGET_DIAL:
		case WIDGET_ARC:
			if (Force || Widget.Position != O->LastPosition)
				lv_arc_set_value(O->Object, Position);
			break;
		case WIDGET_BARGRAPH:
			if (Force || Widget.Position != O->LastPosition)
				lv_bar_set_value(O->Object, Position, LV_ANIM_OFF);
			break;
		case WIDGET_GRAPH:
			/* Time driven, not change driven - a series has to advance even
			   when the reading is identical, or the graph stops telling the
			   truth about time. */
			if (Force || (int32_t)(NowMs - O->NextChartMs) >= 0)
			{
				lv_chart_set_next_value(O->Object,
				                        lv_chart_get_series_next(O->Object, NULL),
				                        Position);
				O->NextChartMs = NowMs + UI_CHART_PERIOD_MS;
			}
			break;
		default:
			break;
		}

		O->LastPosition = Widget.Position;

		if (O->Unit != NULL)
		{
			/* Gauges: the number alone, the unit in its own label. Unit strings
			   are fixed, so identity is enough, as for the name below. */
			snprintf(Text, sizeof(Text), "%s", Widget.Text);
			if (Force || Widget.Unit != O->LastUnit)
			{
				lv_label_set_text(O->Unit, Widget.Unit);
				O->LastUnit = Widget.Unit;
			}
		}
		else
		{
			snprintf(Text, sizeof(Text), "%s %s", Widget.Text, Widget.Unit);
		}

		if ((Force || Widget.State != O->LastState
		     || (int32_t)(NowMs - O->NextTextMs) >= 0)
		    && strcmp(Text, O->LastText) != 0)
		{
			lv_label_set_text(O->Value, Text);
			(void)snprintf(O->LastText, sizeof(O->LastText), "%s", Text);
			O->NextTextMs = NowMs + UI_VALUE_PERIOD_MS;
		}
		else if (Force)
		{
			/* A new face's label starts as "--" from BuildElement; if that is
			   also the text, there is nothing to push, but the cadence still
			   starts now. */
			O->NextTextMs = NowMs + UI_VALUE_PERIOD_MS;
		}

		/* The model returns a pointer to a fixed string, so identity is
		   enough - and the name of a signal does not change within a face
		   anyway. */
		if (O->Label != NULL && (Force || Widget.Label != O->LastLabel))
		{
			lv_label_set_text(O->Label, Widget.Label);
			O->LastLabel = Widget.Label;
		}

		if (Force || Widget.State != O->LastState)
		{
			UiLvgl_Style(O->Object, Widget.State);
			O->LastState = Widget.State;
		}

		O->Primed = true;
	}
}


/***************************************************************************************/
/* Swipe handling. A deliberate gesture only: LVGL reports a direction once the
   touch has travelled far enough, which is what keeps a wet fingertip or a
   bump from changing page. A tap is deliberately ignored. */
void UiLvgl_HandleGesture(void)
{
	lv_dir_t Dir = lv_indev_get_gesture_dir(lv_indev_active());

	/* Signed difference, the same wrap-safe deadline test used in can_link.c:
	   negative means the deadline is still ahead. */
	if ((int32_t)(lv_tick_get() - TransitionUntilMs) < 0)
		return;

	if (Dir == LV_DIR_LEFT)
	{
		Pages_Next();
		PendingAnim = UI_ANIM_PAGE_CHANGE;
	}
	else if (Dir == LV_DIR_RIGHT)
	{
		Pages_Previous();
		PendingAnim = UI_ANIM_PAGE_CHANGE;
	}
}
