/*
 * temp_calibration_data.h
 *
 * GENERATED by tools/gen_temp_calibration_data.py - do not edit by hand.
 *
 * Bench calibration of the ECU's temperature sensors, from
 * roms/3S-GTE/temp_sensor_calibration.xlsx:
 * 84 points against a digital thermometer, ECU value 0..238,
 * covering -34.2 to 100.6 degC.
 *
 * This is the data the curve in convert.xlsx was fitted to, so asserting
 * ecu_scale.c against it closes the loop from measurement to gauge.  The
 * workbook's 5-point alcohol-thermometer set is an earlier and cruder pass
 * and is deliberately not included.
 *
 * Note the measurements repeat some ECU values with readings up to 1.4 degC
 * apart, so the tolerance a test applies here cannot meaningfully be tighter
 * than that - the curve already sits at the noise floor of this data.
 */

#ifndef TEMP_CALIBRATION_DATA_H_
#define TEMP_CALIBRATION_DATA_H_

typedef struct
{
	uint16_t EcuValue;	/* the post-XOR ECU value, integer */
	int16_t MeasuredC100;	/* hundredths of a degree C */
} TempCalibrationPoint_t;

#define TEMP_CALIBRATION_COUNT	(84)

static const TempCalibrationPoint_t TempCalibration[TEMP_CALIBRATION_COUNT] =
{
	{ 238,  10060 },
	{ 237,   9860 },
	{ 236,   9640 },
	{ 236,   9500 },
	{ 235,   9260 },
	{ 233,   9020 },
	{ 232,   8770 },
	{ 230,   8510 },
	{ 229,   8320 },
	{ 228,   8200 },
	{ 227,   8100 },
	{ 227,   7990 },
	{ 226,   7900 },
	{ 225,   7800 },
	{ 225,   7700 },
	{ 224,   7600 },
	{ 223,   7500 },
	{ 222,   7390 },
	{ 221,   7290 },
	{ 220,   7180 },
	{ 219,   7090 },
	{ 218,   6970 },
	{ 216,   6680 },
	{ 215,   6600 },
	{ 214,   6490 },
	{ 211,   6280 },
	{ 210,   6130 },
	{ 208,   6000 },
	{ 207,   5900 },
	{ 205,   5700 },
	{ 203,   5590 },
	{ 202,   5500 },
	{ 199,   5330 },
	{ 197,   5200 },
	{ 195,   5060 },
	{ 194,   4980 },
	{ 192,   4860 },
	{ 183,   4240 },
	{ 175,   3820 },
	{ 165,   3370 },
	{ 157,   3010 },
	{ 151,   2740 },
	{ 141,   2350 },
	{ 136,   2130 },
	{ 120,   1530 },
	{ 113,   1300 },
	{ 111,   1220 },
	{ 106,   1040 },
	{  87,    230 },
	{  86,    190 },
	{  84,    160 },
	{  83,    120 },
	{  82,      0 },
	{  81,    -40 },
	{  80,    -90 },
	{  79,   -120 },
	{  78,   -170 },
	{  75,   -270 },
	{  72,   -360 },
	{  68,   -500 },
	{  67,   -560 },
	{  66,   -600 },
	{  64,   -680 },
	{  63,   -720 },
	{  62,   -800 },
	{  60,   -860 },
	{  58,   -910 },
	{  57,   -990 },
	{  55,  -1050 },
	{  54,  -1120 },
	{  52,  -1200 },
	{  50,  -1270 },
	{  49,  -1350 },
	{  47,  -1400 },
	{  45,  -1500 },
	{  44,  -1580 },
	{  43,  -1600 },
	{  42,  -1660 },
	{  39,  -1760 },
	{  37,  -1840 },
	{  35,  -1960 },
	{  33,  -2040 },
	{  31,  -2140 },
	{   0,  -3420 },
};

#endif /* TEMP_CALIBRATION_DATA_H_ */
