/*
 * ecu_scale.c
 *
 * Raw ECU values -> engineering units.  See ecu_scale.h for the rules callers
 * must follow; this file is where the constants and their provenance live.
 *
 * Every conversion here is either derived from a documented source or checked
 * against one, and the check is repeated in test/test_ecu_scale.c so a wrong
 * constant fails the build rather than showing a plausible-looking gauge.
 * Where a scaling is not established, the function is absent rather than
 * guessed - a gauge that is confidently wrong is worse than one that is
 * obviously missing.
 */

#include "ecu_scale.h"
#include "ecu_scale_tables.h"


/***************************************************************************************/
/* Temperature - ECT, THA, THAM.
 *
 * Table lookup with linear interpolation on the low 8 bits.  The table is
 * generated by tools/gen_ecu_scale_tables.py from the curve in
 * roms/3S-GTE/convert.xlsx; the generator refuses to emit a table that misses
 * its reference points, so a bad curve cannot reach here silently.
 *
 * The table carries one entry past 255 precisely so the interpolation below
 * needs no special case at the top of the range. */
int16_t ECU_ScaleTempC100(uint16_t EcuValueQ8)
{
	uint32_t Index = (uint32_t)(EcuValueQ8 >> 8);
	uint32_t Frac = (uint32_t)(EcuValueQ8 & 0xFFu);
	int32_t Lo = (int32_t)ECU_ScaleTempC100Table[Index];
	int32_t Hi = (int32_t)ECU_ScaleTempC100Table[Index + 1u];

	return (int16_t)(Lo + (((Hi - Lo) * (int32_t)Frac) >> 8));
}


/***************************************************************************************/
/* Engine speed.  rpm = raw / 5.12, and 5.12 is exactly 512/100, so this is
   raw * 100 >> 9 with no rounding error at all.  raw * 100 peaks at 6.55e6,
   well inside uint32. */
uint16_t ECU_ScaleRpm(uint16_t RpmX5p12)
{
	return (uint16_t)(((uint32_t)RpmX5p12 * 100u) >> 9);
}


/***************************************************************************************/
/* Injector 1 pulse width, 4us per bit (ecu.h, from the disassembly).

   A full-scale raw value would be 262140us, so the multiply is done in 32 bits
   and saturated.  Real pulse widths are tens to a few thousand microseconds,
   so saturation only ever fires on a value that was already nonsense. */
uint16_t ECU_ScaleInjPwUs(uint16_t InjPwRaw)
{
	uint32_t Us = (uint32_t)InjPwRaw * 4u;

	return (Us > 0xFFFFu) ? (uint16_t)0xFFFFu : (uint16_t)Us;
}


/***************************************************************************************/
/* Injector duty cycle.
 *
 * For one injection every two crank revolutions the available period is
 * 120e6/rpm microseconds, so
 *
 *     duty_percent_x100 = pw_us * 10000 / (120e6 / rpm)
 *                       = pw_us * rpm / 12000
 *
 * ECU_INJ_DUTY_DIVISOR carries that assumption in one place.  The Gen 3
 * disassembly has both injector_update and injectors_batch_update, and
 * per-injector pulse widths var_inj_pw_inj1..4, so the ECU appears able to
 * fire either sequentially or in a batch.  IF IT IS ACTUALLY BATCH-FIRING -
 * two injections per cycle - the true duty is double what this returns and
 * the divisor below becomes 6000.  Resolve it from the disassembly before
 * trusting the number; changing it is a one-line edit here and nowhere else.
 *
 * The low-rpm guard is not just divide-by-zero protection: below a plausible
 * cranking speed the pulse width and the engine speed are not sampled over
 * anything like the same window, so the quotient is meaningless rather than
 * simply coarse.  Returning zero says "not running" honestly. */
#define ECU_INJ_DUTY_DIVISOR	(12000u)
#define ECU_INJ_DUTY_MIN_RPM	(100u)

uint16_t ECU_ScaleInjDutyPct100(uint16_t InjPwUs, uint16_t Rpm)
{
	uint32_t Duty;

	if (Rpm < ECU_INJ_DUTY_MIN_RPM)
		return 0u;

	/* 65535 * 12800 is 8.4e8 - inside uint32 with room to spare. */
	Duty = ((uint32_t)InjPwUs * (uint32_t)Rpm) / ECU_INJ_DUTY_DIVISOR;

	return (Duty > 0xFFFFu) ? (uint16_t)0xFFFFu : (uint16_t)Duty;
}


/***************************************************************************************/
/* Battery voltage: volts = 0.0774 * raw + 0.0601.
 *
 * From roms/3S-GTE/convert.xlsx and roms/3S-GTE/D151803-9661/
 * battery_voltage_conversion.xlsx, the latter recording it against MCU 9651
 * address 0x56 with four fit points.
 *
 * Note this supersedes the 0.0775 with no offset that toyotune.dbc used to
 * carry - that reads about 0.04V high at charging voltage.
 *
 * In hundredths of a volt that is 7.74 * raw + 6.01, done as
 * (774 * raw + 601) / 100 with a rounding half added.  The divide is a
 * library call on an M0+, which is fine at this frame's 100ms rate. */
uint16_t ECU_ScaleBatteryV100(uint8_t BatteryRaw)
{
	uint32_t Hundredths = (774u * (uint32_t)BatteryRaw) + 601u + 50u;

	return (uint16_t)(Hundredths / 100u);
}


/***************************************************************************************/
/* Manifold absolute pressure.
 *
 * The chain, from roms/3S-GTE/convert.xlsx (which also gives the inverse):
 *
 *     volts     = (pim / 1.285156 + 10560) / 65536 * 5
 *     psi_gauge = (volts - 2.3293) / 0.1025
 *     kpa_abs   = psi_gauge * 6.89476 + 101.325
 *
 * CAREFUL: roms/3S-GTE/gen3/adc_system.md prints this with an x256 term,
 * because it is written for the XDF's 8-bit table byte rather than the 16-bit
 * DMA field.  Substituting var_pim2 into that form is wrong by a factor of
 * about 1.285.  The spreadsheet operates on the 16-bit value directly, as
 * here.
 *
 * Collapsed, the whole chain is linear:
 *
 *     kpa_abs = 0.0039932777 * pim - 1.163821
 *
 * which in tenths of a kPa is 0.03993278 * pim - 11.638.  As Q16 that is a
 * multiplier of 2617 (exactly 2617.03) and an offset of -12, giving under
 * 0.2 kPa of error across the range - far finer than the sensor itself.
 *
 * The offset is why this returns int16: at the sensor's zero-pressure clamp
 * the result is legitimately about -1.2 kPa, and an unsigned return would
 * wrap it to 6553.5 kPa at exactly the moment a fault put it there. */
#define ECU_PIM_Q16_MULT	(2617u)
#define ECU_PIM_KPA10_OFFSET	(-12)

int16_t ECU_ScalePimKpa10(uint16_t PimRaw)
{
	uint32_t Scaled = ((uint32_t)PimRaw * ECU_PIM_Q16_MULT) + 32768u;

	return (int16_t)((int32_t)(Scaled >> 16) + ECU_PIM_KPA10_OFFSET);
}


/***************************************************************************************/
/* Knock retard, about 0.5 degrees per count (ecu.h, from the disassembly).
   Returned as a positive magnitude of retard in hundredths of a degree, so
   255 counts is 127.50 degrees - far beyond anything real, but the type
   carries it rather than wrapping. */
#define ECU_RETARD_DEG100_PER_COUNT	(50)

int16_t ECU_ScaleRetardDeg100(uint8_t RetardRaw)
{
	return (int16_t)((int32_t)RetardRaw * ECU_RETARD_DEG100_PER_COUNT);
}
