#!/usr/bin/env python3
"""Generate ecu_scale_tables.h - the lookup tables ecu_scale.c needs.

Only the temperature sensors need a table.  Everything else in ecu_scale.c is
a linear conversion done in fixed point directly, but ECT/THA/THAM come from
NTC thermistors and are not linear in ADC counts, so no factor/offset can
express them - see hw/dash_cluster/PLAN.md section 3.6.

The curve is not derived here.  It comes from roms/3S-GTE/convert.xlsx, and is
corroborated by two reference points that roms/3S-GTE/gen3/adc_system.md
derived independently from the disassembly, and by 84 measured bench points in
roms/3S-GTE/temp_sensor_calibration.xlsx (RMS 0.40 degC, worst 1.21 degC,
against 1.0-1.4 degC of repeatability in the measurements themselves).  The fit
is at the noise floor of its own calibration data - do not "improve" it.

Run:  python tools/gen_ecu_scale_tables.py -o ecu_scale_tables.h
      python tools/gen_ecu_scale_tables.py --verify ecu_scale_tables.h
"""
import argparse
import sys

# --- the temperature curve, verbatim from convert.xlsx Sheet1 row 8 ---------
#
#   degC = E + F/(G - X) + H/(I - X)
#
# X is the ECU value, i.e. the figure after the ECU's own XOR 0xFF, NOT the
# raw ADC reading.  For THA/THAM that is var_tha / var_tham directly; for ECT
# it is var_ect / 256.0, keeping the two extra bits the 16-bit field carries.
E = 161.034800506902
F = 2639.01416123947
G = 273.34227840271899
H = 94262.143539369397
I = -457.82340934181599

# The table is indexed by the integer part of X and interpolated on the
# fraction, so it needs one entry past 255 for the interpolation at 255.xx.
TEMP_ENTRIES = 257


def temp_c(x):
    """ECU value (may be fractional) -> degrees C."""
    return E + F / (G - x) + H / (I - x)


def temp_table():
    """The table as int16 hundredths of a degree."""
    out = []
    for i in range(TEMP_ENTRIES):
        v = int(round(temp_c(i) * 100.0))
        if not -32768 <= v <= 32767:
            raise SystemExit("entry %d = %d does not fit int16" % (i, v))
        out.append(v)
    return out


# --- reference points, asserted here as well as in the C unit tests ---------
#
# The first two are the sensor-fault defaults documented in adc_system.md from
# the disassembly; the third is convert.xlsx's own worked cell.  They are
# checked at generation time so a bad table can never be written out at all.
REFERENCES = [
    (134.0, 20.0, 1.0, "THA 0x86, adc_system.md says ~20 C"),
    (228.0, 82.0, 1.0, "ECT 0xE400 high byte, adc_system.md says ~82 C"),
    (216.0, 67.165, 0.05, "convert.xlsx's own cell"),
]


def check_references():
    for x, expect, tol, why in REFERENCES:
        got = temp_c(x)
        if abs(got - expect) > tol:
            raise SystemExit(
                "reference check failed: X=%g gave %.3f C, expected %.3f +/- %.3f (%s)"
                % (x, got, expect, tol, why))


def render(table):
    lines = []
    lines.append("/*")
    lines.append(" * ecu_scale_tables.h")
    lines.append(" *")
    lines.append(" * GENERATED by tools/gen_ecu_scale_tables.py - do not edit by hand.")
    lines.append(" * Regenerate with:  python tools/gen_ecu_scale_tables.py -o ecu_scale_tables.h")
    lines.append(" *")
    lines.append(" * Thermistor curve for ECT/THA/THAM, from roms/3S-GTE/convert.xlsx:")
    lines.append(" *")
    lines.append(" *   degC = %.12f" % E)
    lines.append(" *        + %.11f / (%.14f - X)" % (F, G))
    lines.append(" *        + %.12f / (%.14f - X)" % (H, I))
    lines.append(" *")
    lines.append(" * X is the ECU value (post XOR 0xFF), not the raw ADC.  One curve serves")
    lines.append(" * all three sensors.  Validated against the two sensor-fault defaults in")
    lines.append(" * roms/3S-GTE/gen3/adc_system.md and 84 measured points in")
    lines.append(" * roms/3S-GTE/temp_sensor_calibration.xlsx.")
    lines.append(" */")
    lines.append("")
    lines.append("#ifndef ECU_SCALE_TABLES_H_")
    lines.append("#define ECU_SCALE_TABLES_H_")
    lines.append("")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append("/* Hundredths of a degree C, indexed by the integer part of the ECU value.")
    lines.append("   One entry past 255 so interpolation at 255.xx needs no special case. */")
    lines.append("#define ECU_SCALE_TEMP_ENTRIES  (%d)" % TEMP_ENTRIES)
    lines.append("")
    lines.append("static const int16_t ECU_ScaleTempC100Table[ECU_SCALE_TEMP_ENTRIES] =")
    lines.append("{")
    for base in range(0, len(table), 8):
        chunk = table[base:base + 8]
        body = " ".join("%7d," % v for v in chunk)
        lines.append("\t/* %3d */ %s" % (base, body.rstrip()))
    lines.append("};")
    lines.append("")
    lines.append("#endif /* ECU_SCALE_TABLES_H_ */")
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("-o", "--output", help="write the header here")
    ap.add_argument("--verify", metavar="HEADER",
                    help="regenerate and compare against this file; exit 1 on drift")
    ap.add_argument("--dump", action="store_true",
                    help="print the curve at a few points and exit")
    args = ap.parse_args()

    check_references()

    if args.dump:
        print("ECU value -> degC")
        for x in list(range(0, 256, 16)) + [248, 255]:
            print("  %3d 0x%02X  %8.2f" % (x, x, temp_c(x)))
        return 0

    text = render(temp_table())

    if args.verify:
        try:
            with open(args.verify, "r", encoding="utf-8", newline="") as f:
                have = f.read()
        except OSError as exc:
            print("cannot read %s: %s" % (args.verify, exc), file=sys.stderr)
            return 1
        if have.replace("\r\n", "\n") != text:
            print("%s is out of date - regenerate it" % args.verify, file=sys.stderr)
            return 1
        print("%s matches the generator" % args.verify)
        return 0

    if args.output:
        with open(args.output, "w", encoding="utf-8", newline="\n") as f:
            f.write(text)
        print("wrote %s (%d table entries)" % (args.output, TEMP_ENTRIES))
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
