#!/usr/bin/env python3
"""Emit test/temp_calibration_data.h from the bench calibration workbook.

The workbook is roms/3S-GTE/temp_sensor_calibration.xlsx: 84 points taken
against a digital thermometer, ECU value 0..238, covering -34.2 to +100.6 degC.
That set is what the curve in convert.xlsx was fitted to, so asserting the C
implementation against it closes the loop from measurement to gauge.

It also holds a 5-point alcohol-thermometer set - an earlier, cruder pass that
disagrees with the digital data at the top end.  Only the digital set is
emitted; see hw/dash_cluster/PLAN.md section 3.6.

Run:  python tools/gen_temp_calibration_data.py -o test/temp_calibration_data.h
"""
import argparse
import os
import re
import sys
import zipfile
import xml.etree.ElementTree as ET

NS = "{http://schemas.openxmlformats.org/spreadsheetml/2006/main}"

# Sheet1 rows 9..92 hold the digital-thermometer pairs; rows 2..6 are the
# alcohol-thermometer set and are deliberately skipped.
DIGITAL_FIRST_ROW = 9
DIGITAL_LAST_ROW = 92

DEFAULT_XLSX = os.path.join(
    "..", "..", "..", "..", "..", "..", "roms", "3S-GTE",
    "temp_sensor_calibration.xlsx")


def read_pairs(path):
    z = zipfile.ZipFile(path)
    root = ET.fromstring(z.read("xl/worksheets/sheet1.xml"))
    cells = {}
    for c in root.iter(NS + "c"):
        ref = c.get("r")
        v = c.find(NS + "v")
        if v is None or ref is None:
            continue
        m = re.match(r"([A-Z]+)(\d+)", ref)
        if m:
            cells[(m.group(1), int(m.group(2)))] = float(v.text)

    pairs = []
    for row in range(DIGITAL_FIRST_ROW, DIGITAL_LAST_ROW + 1):
        if ("A", row) in cells and ("B", row) in cells:
            pairs.append((cells[("A", row)], cells[("B", row)]))
    return pairs


def render(pairs, source):
    lines = []
    lines.append("/*")
    lines.append(" * temp_calibration_data.h")
    lines.append(" *")
    lines.append(" * GENERATED by tools/gen_temp_calibration_data.py - do not edit by hand.")
    lines.append(" *")
    lines.append(" * Bench calibration of the ECU's temperature sensors, from")
    lines.append(" * %s:" % source)
    lines.append(" * %d points against a digital thermometer, ECU value %d..%d," %
                 (len(pairs), int(min(p[0] for p in pairs)), int(max(p[0] for p in pairs))))
    lines.append(" * covering %.1f to %.1f degC." %
                 (min(p[1] for p in pairs), max(p[1] for p in pairs)))
    lines.append(" *")
    lines.append(" * This is the data the curve in convert.xlsx was fitted to, so asserting")
    lines.append(" * ecu_scale.c against it closes the loop from measurement to gauge.  The")
    lines.append(" * workbook's 5-point alcohol-thermometer set is an earlier and cruder pass")
    lines.append(" * and is deliberately not included.")
    lines.append(" *")
    lines.append(" * Note the measurements repeat some ECU values with readings up to 1.4 degC")
    lines.append(" * apart, so the tolerance a test applies here cannot meaningfully be tighter")
    lines.append(" * than that - the curve already sits at the noise floor of this data.")
    lines.append(" */")
    lines.append("")
    lines.append("#ifndef TEMP_CALIBRATION_DATA_H_")
    lines.append("#define TEMP_CALIBRATION_DATA_H_")
    lines.append("")
    lines.append("typedef struct")
    lines.append("{")
    lines.append("\tuint16_t EcuValue;\t/* the post-XOR ECU value, integer */")
    lines.append("\tint16_t MeasuredC100;\t/* hundredths of a degree C */")
    lines.append("} TempCalibrationPoint_t;")
    lines.append("")
    lines.append("#define TEMP_CALIBRATION_COUNT\t(%d)" % len(pairs))
    lines.append("")
    lines.append("static const TempCalibrationPoint_t TempCalibration[TEMP_CALIBRATION_COUNT] =")
    lines.append("{")
    for x, t in pairs:
        lines.append("\t{ %3d, %6d }," % (int(round(x)), int(round(t * 100.0))))
    lines.append("};")
    lines.append("")
    lines.append("#endif /* TEMP_CALIBRATION_DATA_H_ */")
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("-o", "--output", required=True)
    ap.add_argument("--xlsx", default=DEFAULT_XLSX)
    args = ap.parse_args()

    here = os.path.dirname(os.path.abspath(__file__))
    path = args.xlsx if os.path.isabs(args.xlsx) else os.path.normpath(
        os.path.join(here, args.xlsx))
    if not os.path.exists(path):
        print("cannot find workbook: %s" % path, file=sys.stderr)
        return 1

    pairs = read_pairs(path)
    if len(pairs) < 50:
        print("only %d points read - wrong sheet or row range?" % len(pairs),
              file=sys.stderr)
        return 1

    out = os.path.abspath(args.output)
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w", encoding="utf-8", newline="\n") as f:
        f.write(render(pairs, "roms/3S-GTE/temp_sensor_calibration.xlsx"))
    print("wrote %s (%d points)" % (args.output, len(pairs)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
